language: c

matrix:
  include:
    # Ubuntu trusty
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - gcc
            - g++
            - cmake-data
            - cmake
            - binutils-2.26
            - python3.6
            - curl
            - libglib2.0-dev
            - pkg-config
            - wget
            - unzip
      env:
        - MATRIX_EVAL="curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && sudo python3.6 get-pip.py && alias pip3=pip3.6 && sh .ci/build_ninja.sh && export PATH=/usr/lib/binutils-2.26/bin:${PATH}"

    # Ubuntu xenial
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc
            - g++
            - cmake-data
            - cmake
            - libglib2.0-dev
            - pkg-config
            - python3
            - python3-pip
            - python3-setuptools
            - ninja-build

    # Ubuntu bionic
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - gcc
            - cmake-data
            - cmake
            - libglib2.0-dev
            - pkg-config
            - python3
            - python3-pip
            - python3-setuptools
            - ninja-build
    # macOS
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="brew reinstall glib ninja python@3 python"

    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="brew reinstall glib ninja python"

    - os: osx
      osx_image: xcode10.3
      env:
        - MATRIX_EVAL="brew reinstall glib ninja python"

    - os: osx
      osx_image: xcode11
      env:
        - MATRIX_EVAL="brew reinstall glib ninja python"
before_script:
  - eval "${MATRIX_EVAL}"
  - sudo pip3 install --upgrade pip setuptools wheel
  - sudo pip3 install --upgrade meson
script:
  - mkdir build && cd build
  - cmake ..
  - make -j 2
  - SHLIB_PATH="$(pwd)/../lib" ctest